all:
  children:
    node:
      hosts:
        node1:
          ansible_host: 10.0.2.11
        node2:
          ansible_host: 10.0.2.12
        node3:
          ansible_host: 10.0.2.13
  vars:
    ansible_ssh_user: ivan
    ansible_ssh_pass: ivan
    ansible_sudo_pass: ivan
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    pod_network: 192.168.1.0/16
      

#ansible node -i inventory -m ansible.builtin.shell -a 'rm /etc/apt/sources.list.d/*' -b